### ISSUE TITLE
disable tooltip when locked

### ISSUE THREAD

**Issue by JeanMertz** [lexicalunit/multi-wrap-guide#13]
It would be nice if the hover tooltip showing the column was removed when guides are locked. This serves no purpose on lock, and only clutters the view.

**Comment by lexicalunit** [comment]
I had actually added the tooltip to handle the use case where someone would want to know what the position of the guide is when the guides are locked. If they're unlocked, you can just click on the guide and the column position will be visible in the drag label. But if they're locked, the only way you have to know what position it's in is:
- Go look at the config (I wanted to avoid ever having to go look at the config file)
- Type out a line up the the width of the guide and check the status-bar for the column position (annoying to do in practice)
- Unlock the guides and then click on them (also annoying)

So I added the tooltip as a way to surface that information in a more straightforward and non-obnoxious way. Of course, this was all during initial development. Normally, I have my guides set up in well known positions and I never need to ask myself "what column is this guide at again?" because I already know. So I don't need the tooltip in my day-to-day.

I could certainly add an option for enabling/disabling the tooltips that would work just like locking/unlocking them.

**Comment by lexicalunit** [comment]
Fixed in  9369562 and released with [v0.21.0](https://github.com/lexicalunit/multi-wrap-guide/releases/tag/v0.21.0).

**Comment by JeanMertz** [comment]
Awesome. Thanks!
