### ISSUE TITLE
Uninstalling/Disabling causes problems

### ISSUE THREAD

**Issue by rugk** [lexicalunit/multi-wrap-guide#17]
When you uninstall this package it:
- does _not_ activate `wrap-guide` again
- when you manually enable `wrap-guide` again it - strangely - shows the (vertical) line not at your "preferred line" setting but completely ignores it and shows the vertical line at the position of the most right line which was set before by this package (even if you remove all lines set by this package it just uses the latest line which was there)

The worst thing is: The last change is **persistent**! So actually this package renders the "preferred line" setting ineffective forever.
Would be nice if you could at least say how to (temporarily) (hot)fix the latest error, so I can use the normal Atom settings again.

**Comment by lexicalunit** [comment]
This can definitely be improved. Let me do some testing and see what I can do :+1:

**Comment by lexicalunit** [comment]
Thinking... On your first point:

I could have `multi-wrap-guide` reactivate `wrap-guide` whenever it gets deactivated, but that might not be the correct thing. Say a user has `wrap-guide` deactivated, then they install `multi-wrap-guide`, then they uninstall `multi-wrap-guide`. That'd activate `wrap-guide` for them, which probably isn't what they would want. As a compromise I can make the notice in the documentation about how `multi-wrap-guide` deactivates `wrap-guide` more prominent.

**Comment by lexicalunit** [comment]
Second point:

The right-most vertical line in `multi-wrap-guide` **literally is** your "preferred line" setting. This is so that things like soft word wrap work as you'd expect them to work, as well as anything else in Atom that keys off of the `editor.preferredLineLength` setting. So if you 1) install `multi-wrap-guide`, then 2) move/create a right-most vertical line, and finally 3) uninstall `multi-wrap-guide`... your `editor.preferredLineLength` setting will have changed from the value it was before moving/creating that right-most vertical line.

Again, I could change it so that the left-most vertical line is set to your `editor.preferredLineLength` whenever you deactivate `multi-wrap-guide` but that would be unexpected for users that have set their final right-most vertical line to be their preferred line length already. As a compromise I can make it more clear in the documentation what the right-most line signifies.

**Comment by lexicalunit** [comment]
Third point:

I can't re-create the issue you're having where you can't change your `editor.preferriedLineLength` anymore after uninstalling `multi-wrap-guide`. Can you post your `config.cson` for Atom for debugging purposes?

Note that `multi-wrap-guide` sets grammar-specific `editor.preferriedLineLength` for you, which will override the global `editor.preferriedLineLength` settings when you're viewing files with those grammars. For example, if you set the right-most vertical wrap guide to 120 for Python files, that setting is only valid for Python files. If your global `editor.preferriedLineLength` setting is 80, the 120 setting will override that for Python files. Now say you uninstall `multi-wrap-guide` and re-activate `wrap-guide`. You should still see a wrap-guide at column 120 in Python files, and 80 for all other files. You can change these settings as you wish by editing your `config.cson` file. The grammar specific configurations should be at the bottom on the file.

**Comment by lexicalunit** [comment]
For example:

```
"*":
  editor:
    preferredLineLength: 120
  "multi-wrap-guide":
    columns: [
      73
      80
      100
      120
    ]
".gfm.source":
  editor:
    preferredLineLength: 80
  "multi-wrap-guide":
    columns: [
      73
      80
    ]
```

Given this configuration:
- You'd have a final vertical wrap guide at column 80 in markdown files.
- And you'd have a final vertical wrap guide at column 120 in all other files.

This would be the case for _either_ `wrap-guide` **or** `multi-wrap-guide`.

**Comment by lexicalunit** [comment]
Closing for now but please feel free to update and re-open with more information, hopefully one of my above posts was helpful to you tho! :)
